In [50]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import datasets, linear_model
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.model_selection import train_test_split
import math

In [29]:
XY1 = pd.read_csv('PFQ061B.csv')

SyntaxError: keyword can't be an expression (<ipython-input-29-cb934a53380e>, line 2)

In [30]:
XY1.shape

(1942, 23)

In [35]:
XY1 = XY1[XY1['PFQ061B'] != 5.0]
XY1.shape

(1908, 23)

In [36]:
X = XY1.drop(['PFQ061B','Unnamed: 0'],axis = 1)
Y = XY1[['PFQ061B']]

In [37]:
Y.head()

PFQ061B
0      1.0
1      3.0
2      1.0
3      1.0
4      1.0

In [38]:
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.33, random_state=42)

In [39]:
regr = linear_model.LinearRegression()

In [40]:
regr.fit(X_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [41]:
y_pred = regr.predict(X_test)

In [42]:
print('Coefficients: \n', regr.coef_)

Coefficients: 
 [[ 0.00021507  0.13627767  0.00119774  0.00488993  0.01522898 -0.00305294
   0.00231403 -0.00025186 -0.00117801  0.00157629  0.00430221  0.01180612
   0.01415593  0.12850646  0.04500801 -0.05660079 -0.00865916 -0.02644017
   0.06934589  0.03047314 -0.00174187]]


In [43]:
print('Mean squared error: %.2f'
      % mean_squared_error(y_test, y_pred))

Mean squared error: 0.39


In [54]:
y_pred_rounded = []

for y in y_pred:
    y_pred_rounded.append(y.round())
    

In [55]:
y_pred_rounded

[array([1.]),
 array([1.]),
 array([1.]),
 array([1.]),
 array([1.]),
 array([1.]),
 array([1.]),
 array([1.]),
 array([1.]),
 array([1.]),
 array([1.]),
 array([1.]),
 array([1.]),
 array([1.]),
 array([1.]),
 array([2.]),
 array([1.]),
 array([2.]),
 array([2.]),
 array([1.]),
 array([1.]),
 array([1.]),
 array([1.]),
 array([1.]),
 array([1.]),
 array([1.]),
 array([1.]),
 array([1.]),
 array([2.]),
 array([2.]),
 array([1.]),
 array([1.]),
 array([1.]),
 array([1.]),
 array([1.]),
 array([1.]),
 array([1.]),
 array([1.]),
 array([1.]),
 array([1.]),
 array([1.]),
 array([1.]),
 array([1.]),
 array([1.]),
 array([1.]),
 array([1.]),
 array([1.]),
 array([1.]),
 array([1.]),
 array([2.]),
 array([1.]),
 array([1.]),
 array([1.]),
 array([1.]),
 array([1.]),
 array([2.]),
 array([1.]),
 array([2.]),
 array([1.]),
 array([1.]),
 array([1.]),
 array([1.]),
 array([2.]),
 array([1.]),
 array([1.]),
 array([1.]),
 array([2.]),
 array([1.]),
 array([2.]),
 array([1.]),
 array([1.]),
 array

In [56]:
from sklearn.metrics import accuracy_score

accuracy_score(y_test, y_pred_rounded)

0.7158730158730159

In [57]:
XY1.shape

(1908, 23)

In [58]:
XY1.to_csv('PFQ061B.csv')

In [60]:
# Saving model:
import joblib
joblib.dump(regr, 'regr.sav')

['regr.sav']